export const carArray = [
  {
    carName: "Porsche 918 Spyder",
    imgSrc: "/router-task-yu/Porcheone.png",
    description: "Power(kW)/Power(PS)",
    speed: "309kW/420 PS",
    accel: "4.4s",
    descriptionTwo: "Acceleration 0 - 100 km/h",
    passengers: "2",
    descriptionTree: "Passengers",
  },
  {
    id: 2,
    carName: "BMW M5 Competition 2023",
    imgSrc: "/router-task-yu/BMWM5.svg",
    description: "Power(kW)/Power(PS)",
    speed: "309kW/420 PS",
    accel: "3.8s",
    descriptionTwo: "Acceleration 0 - 100 km/h",
    passengers: "4",
    descriptionTree: "Passengers",
  },
  {
    id: 3,
    carName: "Lamborghini Aventador S",
    imgSrc: "/router-task-yu/Lamba.svg",
    description: "Car info",
    speed: "309kW/420 PS",
    accel: "4.1s",
    descriptionTwo: "Acceleration 0 - 100 km/h",
    passengers: "2",
    descriptionTree: "Passengers",
  },
  {
    id: 4,
    carName: "Lamborghini Aventador S",
    imgSrc: "/router-task-yu/Lamba.svg",
    description: "Car info",
    speed: "309kW/420 PS",
  },
];
